project:
  type: website
  output-dir: "docs"
  preview: 
    port: 6688

website:
  title: "Tom√°s Sou"
  search: 
    location: navbar
    type: overlay  
  navbar:
    left:
      - href: cv.qmd
        text: Portfolio
        icon: file-person
    right:
      - icon: twitter-x
        href: https://x.com/tomas_sou
        target: _blank
      - icon: github 
        href: https://github.com/soutomas
        target: _blank
      - icon: wordpress
        href: https://tomassou.com
        target: _blank
      - icon: envelope
        href: mailto:tomas.sou@carexer.com

format:
  html:
    theme:
      # dark: [cosmo, theme-dark.scss]
      # light: cosmo
      dark: [darkly, theme-dark.scss]
      light: flatly
    css: styles.css
    toc: true
    link-external-newwindow: true
    



