project:
  type: website
  output-dir: "docs"
  preview: 
    port: 6688

website:
  title: "Tom√°s Sou"
  search: 
    location: navbar
    type: overlay  
  navbar:
    left:
      - href: cv.qmd
        text: Portfolio
    right:
      - icon: github 
        href: https://github.com/soutomas
      - icon: twitter-x
        href: https://x.com/tomas_sou
      - icon: envelope
        href: mailto:tomas.sou@carexer.com

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
    



