project:
  type: website
  output-dir: "docs"

website:
  title: "Tom√°s Sou"
  search: 
    location: navbar
    type: overlay  
  navbar:
    left:
      - href: resume.qmd
        text: CV
    right:
      - icon: github 
        href: https://github.com/soutomas
      - icon: twitter
        href: https://x.com/tomas_sou

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true



